[heading "Date" data [Date] format [info 90 edge [size: 0x1] left]] 
[heading "Invoice" data [to-human "Invoice"] format [info 70 edge [size: 1x1] right]] 
[heading "Company" data [to-human "company"] format [info 160 edge [size: 1x1] left]] 
[heading "Type" data [to-human "Type"] format [info 80 edge [size: 1x1] left]] 
[heading "Item" data [to-human "Item"] format [info 140 edge [size: 1x1] left]] 
[heading "Quantity" data [Quantity] format [info 70 edge [size: 1x1] right]] 
[heading "Description" data [Description] format [info 220 edge [size: 1x1] left]]
