[heading "Street1" data [Street1] format [info 200 edge [size: 1x1] left]] 
[heading "Street2" data [Street2] format [info 60 edge [size: 1x1] left]] 
[heading "City" data [City] format [info 100 edge [size: 1x1] left]] 
[heading "StateProv" data [StateProv] format [info 80 edge [size: 1x1] left]] 
[heading "PostalCode" data [PostalCode] format [info 80 edge [size: 1x1] left]] 
[heading "Country" data [Country] format [info 80 edge [size: 1x1] left]]
